---
title: "Alpha vs. genome size"
author: "Stetter"
date: '2017'
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(ggplot2)
library(cowplot)
library(viridis)
alpha_raw <- read.csv("../data/alpha_values.csv",header = T)
```


```{r,fig.width = 12,fig.height=8}

myshapes <- data.frame(name=factor(alpha_raw$genus),
                       num=as.numeric(factor(alpha_raw$genus)))
shapes <- as.numeric(factor(alpha_raw$genus))
shapes <- replace(shapes,shapes<=3,16)
shapes <- replace(shapes,shapes>=9,16)
shapes <- replace(shapes,shapes==6,16)
shapes <- replace(shapes,shapes==7,16)
shapes <- replace(shapes,shapes==4,17) # Helianthus triangle
shapes <- replace(shapes,shapes==8,18)  #Pinus dimond
shapes <- replace(shapes,shapes==5,15)  # Lactuca box
myshapes$shapes <- shapes

aplot <- ggplot(alpha_raw, aes(x=log(genome_1C_mb,10), 
                               y=derived_alpha)) +
 geom_smooth(data=alpha_raw,aes(x=log(genome_1C_mb,10),y=derived_alpha),method = "lm", se = FALSE,color='grey',size=1.5)+
  geom_point(aes(color=genus,size=Ne)) + 
  scale_size_continuous(range = c(4, 18))+ 
  scale_x_continuous(breaks = seq(2, 5.5, by = 0.5),
                     limits = c(2,4.6)) + 
  scale_y_continuous(breaks = seq(0, .6, by = 0.1)) + 
  theme_classic() + 
  theme(text = element_text(face="bold",size = 28),
        axis.ticks.length=unit(3,"mm"),
        axis.title.y = element_text(size = 34,face='bold')) + 
    guides(colour = guide_legend(override.aes = list(size=7))) +
  labs(x = expression(paste(log[10]," Genome size (Mb)")), 
       y = expression(alpha),
       colour = "Genus",size=expression(italic(paste(N[e])))) +
  # Add phylogenetically corrected regression line
  geom_abline(intercept=1.299,slope=-0.378,color='limegreen',size=1.5) +
  theme(axis.text=element_text(size=28),axis.title.x=element_text(size=28,face="bold"))

aplot
ggsave("../figure/Figure3_alpha_GS.pdf",plot = aplot,width = 14,height = 8,dpi = 400)

```
### Get ggplot colors
```{r,fig.width = 12,fig.height=8}
ggplotColours <- function(n = 6, h = c(0, 360) + 15){
  if ((diff(h) %% 360) < 1) h[2] <- h[2] - 360/n
  hcl(h = (seq(h[1], h[2], length = n)), c = 100, l = 65)
}

```


## Helianthus solo
```{r,fig.width = 12,fig.height=8}
heli<- filter(alpha_raw,genus %in% c('Helianthus'))

ggplot(heli, aes(x=genome_1C_mb,y=derived_alpha)) +
 geom_smooth(data=heli,aes(x=genome_1C_mb,y=derived_alpha),method = "lm", se = FALSE,color='grey',size=1.5)+
  geom_point(aes(size=Ne),color=ggplotColours(n=12)[4]) + 
  scale_size_continuous(range = c(4, 18))+ 
  theme(text = element_text(face="bold",size = 18),
        axis.ticks.length=unit(3,"mm")) + 
  labs(x = "Genome size [Mb]", 
       y = expression(alpha),
       colour = "Genus",size=expression(paste(N[e]))) +
  theme(axis.text=element_text(size=24),axis.title=element_text(size=28,face="bold"),text=element_text(size=24))
  # Add phylogenetically corrected regression line


ggsave("../figure/Alpha_GS_helianthus.png",width = 12.5,height = 8)

```
## Pinus solo

```{r,fig.width = 12,fig.height=8}
pinus<- filter(alpha_raw,genus %in% c('Pinus'))

ggplot(pinus, aes(x=genome_1C_mb,y=derived_alpha)) +
 geom_smooth(data=pinus,aes(x=genome_1C_mb,y=derived_alpha),method = "lm", se = FALSE,color='grey',size=1.5)+
  geom_point(aes(size=Ne),color=ggplotColours(n=12)[8]) + 
  scale_size_continuous(range = c(4, 18))+ 
  theme(text = element_text(face="bold",size = 18),
        axis.ticks.length=unit(3,"mm")) + 
  labs(x = "Genome size [Mb]", 
       y = expression(alpha),
       colour = "Genus",size=expression(paste(N[e]))) +
  theme(axis.text=element_text(size=24),axis.title=element_text(size=28,face="bold"),text=element_text(size=24))
  # Add phylogenetically corrected regression line


ggsave("../figure/Alpha_GS_pinus.png",width = 12.5,height = 8)

```
